import type { EquipmentItem, LoadoutOption, LoadoutOptionItem, ShipDetail, SlotDef } from "./builderTypes";
import { isCompatibleWithShip, isObtainable } from "./builderHelpers";

/**
 * Approximate the game's own shipyard "Minimum/Low/Medium/High Preset" loadouts.
 *
 * The real ones are generated by the compiled game engine (`C.GetLoadoutsInfo`, called from
 * `ui/addons/ego_detailmonitor/menu_ship_configuration.lua`) — there is no game file that
 * defines them, so this can't be "extracted." It's a heuristic reconstruction derived from 16
 * real saved-loadout samples across 4 ships (S/M/L, fighter/trader/destroyer), cross-referenced
 * against our own price/mk/licence data:
 *
 *   - Every hardware kind (engine/thruster/shield/weapon/turret) is chosen by ranking the
 *     ship-compatible, player-*obtainable* equipment for that kind+size by price — obtainable
 *     meaning the same "no restriction, or a general-use restriction, or a licence the player
 *     actually owns" check the Ship Builder's own "Obtainable Only" toggle already uses. This
 *     was the key finding: two ships showed weapon prices strictly climbing Low→Medium→High
 *     while DPS did *not* — price-among-obtainable-items is the axis, not raw stat quality, and
 *     it explains why picks span multiple factions/makers (whatever the player has licenced).
 *   - Minimum only equips the mandatory kinds (engine, thruster) — shields/weapons/turrets are
 *     left empty in every sample.
 *   - Low fills every kind at the cheapest obtainable price; Medium picks the middle of the
 *     ranked list; High picks the priciest.
 *   - Software follows its own fixed mk schedule (identical in every sample):
 *       flightassist mk1, target mk1, trade mk1 always when present.
 *       scannerlongrange: mk1 through Low, mk2 from Medium on.
 *       scannerobject:    mk1 at Minimum only, mk2 from Low on.
 *       dock: absent at Minimum, mk1 at Low, mk2 from Medium on.
 *       Minimum includes exactly one of target/trade, chosen by the ship's own role
 *       (`role === "trade"` → trade, else target) — Low/Medium/High always include both.
 *   - Not modeled (no samples showed it, so left unfilled rather than guessed): consumables
 *     (missiles/countermeasures/deployables/drones), economy/mining-scanner software, and the
 *     L/XL "pack 2 units into one connection group" scaling occasionally seen at High.
 *
 * This is explicitly an approximation, not game data — always label it as such in the UI.
 */

const HARDWARE_KINDS = ["engine", "thruster", "shield", "weapon", "turret"] as const;
const MANDATORY_KINDS = new Set(["engine", "thruster"]);

type Tier = "minimum" | "low" | "medium" | "high";
const TIER_LABELS: Record<Tier, string> = {
  minimum: "Minimum",
  low: "Low",
  medium: "Medium",
  high: "High",
};

function poolFor(
  kind: string,
  size: string,
  ship: ShipDetail,
  equipment: EquipmentItem[],
  licenceSet: Set<string>,
): EquipmentItem[] {
  const shipFid = ship.owner_factions?.[0] ?? null;
  return equipment
    .filter(e => e.kind === kind && e.size?.toLowerCase() === size.toLowerCase())
    .filter(e => isCompatibleWithShip(e, ship.ship_id))
    .filter(e => isObtainable(e, licenceSet, shipFid))
    .sort((a, b) => (a.price_avg ?? 0) - (b.price_avg ?? 0));
}

function pick(pool: EquipmentItem[], percentile: number): EquipmentItem | undefined {
  if (pool.length === 0) return undefined;
  return pool[Math.round(percentile * (pool.length - 1))];
}

function softwarePool(type: string, equipment: EquipmentItem[]): EquipmentItem[] {
  return equipment.filter(e => e.kind === "software" && e.size === type).sort((a, b) => (a.mk ?? 0) - (b.mk ?? 0));
}

function softwareByMk(type: string, mk: number, equipment: EquipmentItem[]): EquipmentItem | undefined {
  const pool = softwarePool(type, equipment);
  return pool.find(e => e.mk === mk) ?? pool[pool.length - 1];
}

/** Build the four approximate-tier options for one ship. Returns [] if the ship has no
 * hardware slots at all (shouldn't happen for a real ship, but keeps callers simple). */
export function buildApproximatePresets(
  ship: ShipDetail,
  slots: SlotDef[],
  equipment: EquipmentItem[],
  licenceSet: Set<string>,
): LoadoutOption[] {
  const slotCounts = new Map<string, number>(); // "kind:size" -> count
  for (const s of slots) {
    if (!HARDWARE_KINDS.includes(s.kind as (typeof HARDWARE_KINDS)[number])) continue;
    const key = `${s.kind}:${s.size}`;
    slotCounts.set(key, (slotCounts.get(key) ?? 0) + 1);
  }

  const wantsTrade = ship.role === "trade";

  const tiers: Tier[] = ["minimum", "low", "medium", "high"];
  return tiers.map(tier => {
    const items: LoadoutOptionItem[] = [];

    for (const [key, count] of slotCounts) {
      const [kind, size] = key.split(":");
      if (tier === "minimum" && !MANDATORY_KINDS.has(kind)) continue; // optional kinds stay empty

      const pool = poolFor(kind, size, ship, equipment, licenceSet);
      const percentile = tier === "minimum" || tier === "low" ? 0 : tier === "medium" ? 0.5 : 1;
      const chosen = pick(pool, percentile);
      if (chosen) items.push({ kind, ware_id: chosen.ware_id, quantity: count });
    }

    const addSoftware = (type: string, mk: number) => {
      const chosen = softwareByMk(type, mk, equipment);
      if (chosen) items.push({ kind: "software", ware_id: chosen.ware_id, quantity: 1 });
    };
    addSoftware("flightassist", 1);
    addSoftware("scannerlongrange", tier === "minimum" || tier === "low" ? 1 : 2);
    addSoftware("scannerobject", tier === "minimum" ? 1 : 2);
    if (tier === "minimum") {
      addSoftware(wantsTrade ? "trade" : "target", 1);
    } else {
      addSoftware("target", 1);
      addSoftware("trade", 1);
      if (tier !== "low") addSoftware("dock", 2);
      else addSoftware("dock", 1);
    }

    return {
      loadout_id: `approx-${tier}`,
      name: TIER_LABELS[tier],
      description: null,
      source: "approx" as const,
      items,
    };
  });
}
